### ISSUE TITLE
Node name ambiguity (ConvertSfmData)

### ISSUE THREAD

**Issue by almarouk** [alicevision/MeshroomResearch#21]
There's already a node in Meshroom called 'ConvertSfmFormat' that can be confused with the MRRS node 'ConvertSfmData'.
Suggestion to change the name from 'ConvertSfmData' to 'ConvertSfmToNerf' for example.

https://github.com/alicevision/MeshroomResearch/blob/7910b861daa9e2c73229b5393d130d48c4288dd3/mrrs/nodes/implicit/ConvertSfmData.py#L134

**Comment by mh0g** [comment]
moved!
